[package]
name = "opencrate"
description = "One-dependency entry point for the Open Crate Rust core"
repository = "https://github.com/AlexiAxAxA/OpenCrate"
homepage = "https://closecrate.com/"
readme = "README.md"
version = "0.0.2"
edition.workspace = true
rust-version.workspace = true
license-file = "../../LICENSE-OPENCRATE"
publish.workspace = true

[features]
app-data = ["dep:opencrate-sdk"]

[dependencies]
oc-policy = { version = "=0.0.2", path = "../oc-policy" }
oc-crypto = { version = "=0.0.2", path = "../oc-crypto" }
oc-format = { version = "=0.0.2", path = "../oc-format" }
oc-protocol = { version = "=0.0.2", path = "../oc-protocol" }
oc-engine = { version = "=0.0.2", path = "../oc-engine" }
opencrate-sdk = { version = "=0.0.2", optional = true }

[[example]]
name = "seal-file"
path = "examples/seal-file.rs"
required-features = ["app-data"]

[lints]
workspace = true
